main: dk.muj.derius.Derius
name: Derius-Core
version: 0.2_dev
#website: http://muj.dk/Derius
authors: [madus, ulumulu1510]
description: §eDerius is an open skill framework
depend: [MassiveCore]
softdepend: [Factions]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  derius.ability.use: {description: use ability, default: false}
  derius.ability.see: {description: see ability, default: false}
  derius.admin: {description: admin mode, default: false}
  derius.basecommand: {description: derius basecommand, default: false}
  derius.clean: {description: clean data, default: false}
  derius.clean.skill.all: {description: clean every skill, default: false}
  derius.clean.player: {description: clean yourself, default: false}
  derius.clean.player.other: {description: clean another player, default: false}
  derius.clean.player.all: {description: clean all players, default: false}
  derius.debug: {description: debug information, default: false}
  derius.inspect: {description: inspect player, default: false}
  derius.inspect.other: {description: inspect other players, default: false}
  derius.keys: {description: ability activation keys, default: false}
  derius.keys.abilityid: {description: get all ability ids, default: false}
  derius.keys.add: {description: add key, default: false}
  derius.keys.clear: {description: clear keys, default: false}
  derius.keys.list: {description: list keys, default: false}
  derius.keys.remove: {description: remove key, default: false}
  derius.list: {description: list skills, default: false}
  derius.notify.chunk: {description: get notified on chunk cleanup, default: false}
  derius.skill: {description: skill information, default: false}
  derius.skill.learn: {description: learn skill, default: false}
  derius.skill.see: {description: see skill, default: false}
  derius.sp: {description: specialisation basecommand, default: false}
  derius.sp.info: {description: specialisation info, default: false}
  derius.sp.learn: {description: specialise in skill, default: false}
  derius.sp.list: {description: list specialisation, default: false}
  derius.sp.list.other: {description: list others specialisations, default: false}
  derius.sp.unlearn: {description: unspecialise in skill, default: false}
  derius.version: {description: show plugin version, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  derius.*:
    default: false
    children:
      derius.ability.use: true
      derius.ability.see: true
      derius.admin: true
      derius.basecommand: true
      derius.clean: true
      derius.clean.skill.all: true
      derius.clear.player: true
      derius.clear.player.other: true
      derius.clean.player.all: true
      derius.debug: true
      derius.inspect: true
      derius.inspect.other: true
      derius.keys: true
      derius.keys.abilityid: true
      derius.keys.add: true
      derius.keys.clear: true
      derius.keys.list: true
      derius.keys.remove: true
      derius.list: true
      derius.notify.chunk: true
      derius.skill: true
      derius.skill.learn: true
      derius.skill.see: true
      derius.sp: true
      derius.sp.info: true
      derius.sp.learn: true
      derius.sp.list: true
      derius.sp.list.other: true
      derius.sp.unlearn: true
      derius.version: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  derius.kit.op:
    default: op
    children:
      derius.*: true
  derius.kit.rank3:
    default: false
    children:
      derius.kit.rank2: true
  derius.kit.rank2:
    default: false
    children:
      derius.debug: true
      derius.kit.rank1: true
  derius.kit.rank1:
    default: false
    children:
      derius.notify.chunk: true
      derius.kit.rank0: true
  derius.kit.rank0:
    default: false
    children:
      derius.basecommand: true
      derius.inspect: true
      derius.inspect.other: true
      derius.list: true
      derius.clean.player: true
      derius.sp: true
      derius.sp.info: true
      derius.sp.learn: true
      derius.sp.list: true
      derius.sp.list.other: true
      derius.sp.unlearn: true
# -------------------------------------------- #
# DEFAULT
# -------------------------------------------- #
  derius.kit.default:
    default: true
    children:
      derius.kit.rank0: true
